### ISSUE TITLE
Example with windows-build-uwp-461/Dockerfile

### ISSUE THREAD

**Issue by MofaggolHoshen** [coderobin/windows-container#1]
Can you give an example with windows-build-uwp-461/Dockerfile

**Comment by xied75** [comment]
@summoncse the naming of "windows-build-uwp-461" is wrong historically, it was in fact a simple build container for a Portable Library (PCL) that supports UWP, .NET 4.61. I used it to build one of my libraries for my UWP App to consume.

In order to build the actual UWP App with a container, I would need to create a new container, and probably UWP version specific. This was in my back log that hasn't got high priorities yet.

I must say without the need of a full CI/CD pipeline, build UWP App with a container isn't that useful to normal developers. You can just fire up Visual Studio and get things done, or use VSTS. The original plan for my project is to use a container to build the app, and deploy onto the hosting Windows Server, fire up auto UI testing on it, when everything pass, with some kind of switch to start the deployment to Store all done in code. If you are thinking something similar, then sure we probably can work on this together.
